markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Kerry Walker
tagline:          'Random Stuff'
description:      'Software Engineer, Forgetful Blogger, Lucky Husband, Proud Father'
url:              https://www.kerrywalker.uk
baseurl:          /

author:
  name:           'Kerry Walker'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/KerryWalker/KerryWalker.github.io
