# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kerry Walker
tagline:          ''
description:      'Software Engineer, Neglectful Blogger, Lucky Husband, Proud Father .'
url:              http://www.kerrywalker.uk
baseurl:          /

author:
  name:           'Kerry Walker'
  url:            http://www.kerrywalker.uk

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/KerryWalker/KerryWalker.github.io
